import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  ...compat.config({
    rules: {
      "@typescript-eslint/no-array-constructor": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-for-in-array": "off",
      "@typescript-eslint/no-implied-eval": "off",
      "@typescript-eslint/no-inferrable-types": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-wrapper-object-types": "off",
      "@typescript-eslint/no-unnecessary-type-constraint": "off",
      "@typescript-eslint/no-unnecessary-type-constraints": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "react/react-in-jsx-scope": "off",
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
      "jsx-a11y/alt-text": "off",
      "jsx-a11y/anchor-is-valid": "off",
      "import/no-unresolved": "off",
      "import/prefer-default-export": "off",
      "no-console": "off",
      "no-unused-vars": "off",
      "no-shadow": "off",
      "no-undef": "off",
      "no-empty": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-trailing-spaces": "off",
      "object-curly-spacing": "off",
      "react/jsx-no-undef": "off",
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "off",
      semi: "off",
      quotes: "off",
      indent: "off",
      "comma-dangle": "off",
      "arrow-body-style": "off",
      "prefer-arrow-callback": "off",
      "prefer-const": "off",
      "template-curly-spacing": "off",
      "space-before-function-paren": "off",
      "spaced-comment": "off",
      "eol-last": "off",
      "keyword-spacing": "off",
      "space-infix-ops": "off",
      "object-shorthand": "off",
      "array-bracket-spacing": "off",
      "computed-property-spacing": "off",
      "block-spacing": "off",
      "brace-style": "off",
      "arrow-spacing": "off",
      "no-var": "off",
      "prefer-template": "off",
      eqeqeq: "off",
      "no-multi-spaces": "off",
      "no-multiple-empty-lines": "off",
      "max-len": "off",
      "import/extensions": "off",
      "import/no-extraneous-dependencies": "off",
      "import/order": "off",
      "jsx-quotes": "off",
      "react/jsx-curly-spacing": "off",
      "react/jsx-indent": "off",
      "react/jsx-indent-props": "off",
      "react/prop-types": "off",
      "react/function-component-definition": "off",
      "react/no-array-index-key": "off",
      "react/no-unescaped-entities": "off",
      "react/self-closing-comp": "off",
      "react/jsx-filename-extension": "off",
      "react/jsx-props-no-spreading": "off",
      "react/no-children-prop": "off",
      "jsx-a11y/click-events-have-key-events": "off",
      "jsx-a11y/no-static-element-interactions": "off",
      "jsx-a11y/no-noninteractive-element-interactions": "off",
      "jsx-a11y/label-has-associated-control": "off",
      "jsx-a11y/control-has-associated-label": "off",
      "jsx-a11y/tabindex-no-positive": "off",
      "jsx-a11y/interactive-supports-focus": "off",
    },
  }),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
